<template>
  <div class="p-6">
    <!-- Page Header -->
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-gray-800 mb-2">Reports & Analytics</h1>
      <p class="text-gray-600">Generate and view comprehensive business reports</p>
    </div>

    <!-- Report Type Selection -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
      <button 
        v-for="type in reportTypes" 
        :key="type.id"
        @click="selectedReportType = type.id"
        :class="[
          'p-6 rounded-lg border-2 transition-all text-left',
          selectedReportType === type.id 
            ? 'border-blue-500 bg-blue-50' 
            : 'border-gray-200 hover:border-blue-300 bg-white'
        ]"
      >
        <div :class="`w-12 h-12 ${type.iconBg} rounded-lg flex items-center justify-center mb-4`">
          <svg class="w-6 h-6" :class="type.iconColor" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" :d="type.iconPath"/>
          </svg>
        </div>
        <h3 class="font-semibold text-gray-800 mb-1">{{ type.name }}</h3>
        <p class="text-sm text-gray-600">{{ type.description }}</p>
      </button>
    </div>

    <!-- Report Filters -->
    <div class="bg-white rounded-lg shadow-md p-6 mb-6">
      <h3 class="font-semibold text-gray-800 mb-4">Report Parameters</h3>
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">From Date</label>
          <input 
            v-model="reportFilters.fromDate"
            type="date" 
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">To Date</label>
          <input 
            v-model="reportFilters.toDate"
            type="date" 
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Department</label>
          <select v-model="reportFilters.department" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
            <option value="">All Departments</option>
            <option value="sales">Sales</option>
            <option value="operations">Operations</option>
            <option value="it">IT Department</option>
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Format</label>
          <select v-model="reportFilters.format" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
            <option value="pdf">PDF</option>
            <option value="excel">Excel</option>
            <option value="csv">CSV</option>
          </select>
        </div>
      </div>
      <div class="mt-4 flex gap-3">
        <button @click="generateReport" class="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg flex items-center gap-2 transition-all">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
          </svg>
          Generate Report
        </button>
        <button class="bg-gray-100 hover:bg-gray-200 text-gray-700 px-6 py-2 rounded-lg transition-all">
          Reset Filters
        </button>
      </div>
    </div>

    <!-- Recent Reports -->
    <div class="bg-white rounded-lg shadow-md overflow-hidden">
      <div class="px-6 py-4 border-b border-gray-200">
        <h3 class="font-semibold text-gray-800">Recent Reports</h3>
      </div>
      <div class="overflow-x-auto">
        <table class="w-full">
          <thead class="bg-gray-50 border-b border-gray-200">
            <tr>
              <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Report Name</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Type</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Period</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Generated By</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Date</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Status</th>
              <th class="px-6 py-4 text-right text-xs font-semibold text-gray-600 uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <tr v-for="report in recentReports" :key="report.id" class="hover:bg-gray-50 transition-colors">
              <td class="px-6 py-4">
                <div class="flex items-center gap-3">
                  <div :class="`w-10 h-10 ${report.iconBg} rounded-lg flex items-center justify-center`">
                    <svg class="w-5 h-5" :class="report.iconColor" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                    </svg>
                  </div>
                  <span class="font-medium text-gray-800">{{ report.name }}</span>
                </div>
              </td>
              <td class="px-6 py-4">
                <span :class="`px-3 py-1 ${report.typeBadge} rounded-full text-sm font-medium`">
                  {{ report.type }}
                </span>
              </td>
              <td class="px-6 py-4 text-gray-700">{{ report.period }}</td>
              <td class="px-6 py-4 text-gray-700">{{ report.generatedBy }}</td>
              <td class="px-6 py-4 text-gray-700">{{ formatDate(report.date) }}</td>
              <td class="px-6 py-4">
                <span :class="`px-3 py-1 ${report.statusBadge} rounded-full text-sm font-medium`">
                  {{ report.status }}
                </span>
              </td>
              <td class="px-6 py-4 text-right">
                <button @click="downloadReport(report)" class="text-blue-600 hover:text-blue-800 mr-3">Download</button>
                <button @click="deleteReport(report.id)" class="text-red-600 hover:text-red-800">Delete</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';

// Report types
const reportTypes = ref([
  {
    id: 'sales',
    name: 'Sales Report',
    description: 'Revenue and transaction analysis',
    iconBg: 'bg-green-100',
    iconColor: 'text-green-600',
    iconPath: 'M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z'
  },
  {
    id: 'attendance',
    name: 'Attendance Report',
    description: 'Employee presence and hours',
    iconBg: 'bg-blue-100',
    iconColor: 'text-blue-600',
    iconPath: 'M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z'
  },
  {
    id: 'inventory',
    name: 'Inventory Report',
    description: 'Stock levels and movements',
    iconBg: 'bg-purple-100',
    iconColor: 'text-purple-600',
    iconPath: 'M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4'
  },
  {
    id: 'performance',
    name: 'Performance Report',
    description: 'Team and individual metrics',
    iconBg: 'bg-orange-100',
    iconColor: 'text-orange-600',
    iconPath: 'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z'
  }
]);

const selectedReportType = ref('sales');

// Report filters
const reportFilters = ref({
  fromDate: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString().split('T')[0],
  toDate: new Date().toISOString().split('T')[0],
  department: '',
  format: 'pdf'
});

// Recent reports
const recentReports = ref([
  {
    id: 1,
    name: 'Monthly Sales Summary',
    type: 'Sales',
    typeBadge: 'bg-green-100 text-green-700',
    period: 'Jan 1 - Jan 31, 2024',
    generatedBy: 'John Doe',
    date: '2024-02-01',
    status: 'Ready',
    statusBadge: 'bg-green-100 text-green-700',
    iconBg: 'bg-green-100',
    iconColor: 'text-green-600'
  },
  {
    id: 2,
    name: 'Weekly Attendance',
    type: 'Attendance',
    typeBadge: 'bg-blue-100 text-blue-700',
    period: 'Feb 5 - Feb 11, 2024',
    generatedBy: 'Alice Smith',
    date: '2024-02-11',
    status: 'Ready',
    statusBadge: 'bg-green-100 text-green-700',
    iconBg: 'bg-blue-100',
    iconColor: 'text-blue-600'
  },
  {
    id: 3,
    name: 'Inventory Stock Level',
    type: 'Inventory',
    typeBadge: 'bg-purple-100 text-purple-700',
    period: 'As of Feb 11, 2024',
    generatedBy: 'Bob Johnson',
    date: '2024-02-11',
    status: 'Processing',
    statusBadge: 'bg-orange-100 text-orange-700',
    iconBg: 'bg-purple-100',
    iconColor: 'text-purple-600'
  },
  {
    id: 4,
    name: 'Q4 Performance Review',
    type: 'Performance',
    typeBadge: 'bg-orange-100 text-orange-700',
    period: 'Oct - Dec 2023',
    generatedBy: 'Maria Garcia',
    date: '2024-01-15',
    status: 'Ready',
    statusBadge: 'bg-green-100 text-green-700',
    iconBg: 'bg-orange-100',
    iconColor: 'text-orange-600'
  }
]);

// Helper functions
const formatDate = (date) => {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  });
};

// Actions
const generateReport = () => {
  console.log('Generating report:', {
    type: selectedReportType.value,
    filters: reportFilters.value
  });
  alert('Report generation started. You will be notified when it\'s ready.');
};

const downloadReport = (report) => {
  console.log('Downloading report:', report);
  alert(`Downloading ${report.name}...`);
};

const deleteReport = (reportId) => {
  if (confirm('Are you sure you want to delete this report?')) {
    recentReports.value = recentReports.value.filter(r => r.id !== reportId);
  }
};
</script>